### ISSUE TITLE
Table schema missing default value

### ISSUE THREAD

**Issue by LeoOnTheEarth** [asika32764/JConsole#3]
When import data to an empty database, the default value of the table schema will missing.

For example:

``` yaml
'#__assets':
    name: '#__assets'
    from:
        - '#__assets'
    columns:
        id: { Field: id, Type: 'int(10) unsigned', 'Null': NO, Default: null, Extra: auto_increment, Comment: 'Primary Key', From: [id] }
        parent_id: { Field: parent_id, Type: int(11), 'Null': NO, Default: '0', Extra: '', Comment: 'Nested set parent.', From: [parent_id] }
        lft: { Field: lft, Type: int(11), 'Null': NO, Default: '0', Extra: '', Comment: 'Nested set lft.', From: [lft] }
        rgt: { Field: rgt, Type: int(11), 'Null': NO, Default: '0', Extra: '', Comment: 'Nested set rgt.', From: [rgt] }
        level: { Field: level, Type: 'int(10) unsigned', 'Null': NO, Default: null, Extra: '', Comment: 'The cached level in the nested tree.', From: [level] }
        name: { Field: name, Type: varchar(50), 'Null': NO, Default: null, Extra: '', Comment: "The unique name for the asset.\n", From: [name] }
        title: { Field: title, Type: varchar(100), 'Null': NO, Default: null, Extra: '', Comment: 'The descriptive title for the asset.', From: [title] }
        rules: { Field: rules, Type: varchar(5120), 'Null': NO, Default: null, Extra: '', Comment: 'JSON encoded access control.', From: [rules] }

```

Result table schema as below:

``` SQL
CREATE TABLE `pcr_assets` (
 `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Primary Key',
 `parent_id` int(11) NOT NULL COMMENT 'Nested set parent.',
 `lft` int(11) NOT NULL COMMENT 'Nested set lft.',
 `rgt` int(11) NOT NULL COMMENT 'Nested set rgt.',
 `level` int(10) unsigned NOT NULL COMMENT 'The cached level in the nested tree.',
 `name` varchar(50) NOT NULL COMMENT 'The unique name for the asset.\n',
 `title` varchar(100) NOT NULL COMMENT 'The descriptive title for the asset.',
 `rules` varchar(5120) NOT NULL COMMENT 'JSON encoded access control.',
 PRIMARY KEY (`id`),
 UNIQUE KEY `idx_asset_name` (`name`),
 KEY `idx_lft_rgt` (`lft`,`rgt`),
 KEY `idx_parent_id` (`parent_id`)
) ENGINE=InnoDB AUTO_INCREMENT=58 DEFAULT CHARSET=utf8
```
# __assets.parent_id has a default: '0', but after importing the default value in the database is "NULL"
